# Generated by Django 5.0.4 on 2024-05-09 10:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(default="I'm [Your Name], a passionate Django and Python developer with a knack for crafting efficient, scalable, and user-friendly web applications. With years of experience in full-stack development, I specialize in building robust backend systems, seamless APIs, and dynamic frontend interfaces using the latest web technologies."),
            preserve_default=False,
        ),
    ]
